### PR TITLE
VisionComponent SceneCaptures as Editable UProperties & Depth CaptureSource Change

### PR DESCRIPTION
**Pull request by Tim-Fronsee**
#### Summary

Raises Color, Depth, and Image captures to be public and editable (via UE4 Editor / Blueprints), and tweaks the depth capture.

##### Design Change

- Converts the Depth `CaptureSource` to `SceneDepth` instead of `FinalColorLDR`

The reasoning for this change is that the UE4 post processing may impact the depth image with the prior implementation (in my case the depth image was entirely white).  

- Sets the Depth `TextureTarget` to `RGBA16f` 
- Divides the depth data by 100 to convert from UU (cm) to meters

##### Others 

- Removed some warning logs from the `VisionComponent` constructor.
- Removed `ShowFlagsPostProcess` since the 

Please let me know if you'd like the logs to remain, though perhaps at a higher log level.

### CODE REVIEW

**Comment by Sanic** [comment]
Hi @Tim-Fronsee 
On which version of UE4 did you encounter the problems with the depth images?

After you've changed the CaptureSource, do you still need the following call:
https://github.com/code-iai/ROSIntegrationVision/blob/master/Source/ROSIntegrationVision/Private/VisionComponent.cpp#L81
? What happens if you remove it?

**Comment by Tim-Fronsee** [comment]
I use UE4.24.1.

The issue with the depth image occurred after I had created a post processing effect for my simulation.  Without post processing effects, the depth image was fine on the same version of UE4.

The block you highlighted is not needed with the SceneDepth capture source.  I updated the PR to remove the `SceneDepth` asset and the block referencing it.  

Below are a couple images to show the effects of the latest commit.

##### Depth Image (in RVIZ)
image

##### Depth Cloud (in RVIZ)
image

**Comment by Sanic** [comment]
Good to hear that we could get rid of the depth material asset.
I just wonder how this change would affect earlier versions of UE4 as not everybody might be as cutting-edge as you are 😃 Do you have experience with other versions?

**Comment by Tim-Fronsee** [comment]
I previously used UE4.23, but I experienced issues with the Vulkan command buffer (on Linux) in that version so I migrated to 4.24.  

I don't believe this change will affect prior versions of Unreal unless there are changes related to the Scene Depth capture source.  

I ran a diff using git to check for references of `SCS_SceneDepth` and I see it referenced as far back as UE4.17 (the oldest version supported by [ROSIntegration](https://github.com/code-iai/ROSIntegration)).   It might exist on prior versions, but I didn't diff further than 4.17.
```
$ git diff origin/4.17 | grep -i 'SCS_SceneDepth'
 	SCS_SceneDepth UMETA(DisplayName="SceneDepth in R"),
 IMPLEMENT_MOBILE_SCENE_CAPTURECOPY(SCS_SceneDepth);
 		case SCS_SceneDepth:
 			return SetCaptureToTargetShaders<bDemosaic, SCS_SceneDepth>(RHICmdList, GraphicsPSOInit, View, SourceTexSize, SourceTextureRHI);
-			else if (SceneCaptureSource == SCS_SceneDepth)
-				TShaderMapRef<TSceneCapturePS<SCS_SceneDepth> > PixelShader(View.ShaderMap);
+				else if (SceneCaptureSource == SCS_SceneDepth)
+					TShaderMapRef<TSceneCapturePS<SCS_SceneDepth> > PixelShader(View.ShaderMap);

```

If you'd like me to test a specific version (or versions) let me know and I'll give it a shot.

**Comment by Sanic** [comment]
Hi @Tim-Fronsee 
It would be cool if you could check if it works with 4.22 as i think many people still use it.

**Comment by Tim-Fronsee** [comment]
@Sanic 
All of the following were captured using UE4.22.3.

First, I'd like to better illustrate the issue itself.

#### Using FinalColor with No Post Processing:

image

Depth data is correct.

#### Using FinalColor with a Post Processing Volume & Material:

image

There is a post processing material only on the cone mesh, but notice how the entire capture is effected by the Post Processing Volume, causing it to appear flat.  The post processing is visible inside both the Color (the rainbow-esque highlight) and the Depth image.  

The depth image is completely black except for a small triangle from the post processing effect.  
I changed RVIZ's camera angle slightly to show how the small triangle appears behind the rest of the scene's depth cloud.

-------

Now for the solution provided in this PR (verified on UE4.24.1 & UE4.22.3).

#### Using SceneDepth in R with a Post Processing Volume & Material

image

Note the rainbow highlight around the cone in the Color image, showing the post processing effect is live.

**Comment by Sanic** [comment]
Thanks for the very detaillled information and the PR in general.

**Pull request merged**
