### PR TITLE
Fix DisableTFPublishing Editor Crash

### PR DESCRIPTION
**Pull request by Tim-Fronsee**
### Bug Steps to Reproduce

- Attach a Vision component to an Actor with `DisableTFPublishing` initialized to **true**
- In the Editor, toggle `DisableTFPublishing` 

### Fix 

The crash is caused by an uninitialized `_TFPublisher` which is referenced when `DisableTFPublishing` is set to **false** after initialized with **true**

### CODE REVIEW

**Comment by Sanic** [comment]
Hi Tim,

thanks for the PR.
If i understand this correctly, this will now cause the TF Publisher to always call advertise(). Is this correct? This might be a bit confusing when debugging because the TFPublisher will show up as a publisher on /tf even though it will not send anything to that topic.

**Comment by Tim-Fronsee** [comment]
@Sanic 

Good point. 

I updated my PR with a new design that toggles TF's advertising based on the `DisableTFPublishing` flag and whether or not the topic is already publishing.  

Additionally, I fixed a `RootComponent` reference I missed in a prior PR (apologies).

**Comment by Tim-Fronsee** [comment]
I opened a [PR](https://github.com/code-iai/ROSIntegration/pull/105) in `ROSIntegration` for a new function to return the internal `Avertised` flag from a topic, thus this PR now depends on the aforementioned PR.

**Comment by Sanic** [comment]
That looks better! Thank you

**Pull request merged**
